Config file config/config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Provided cores: 8
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                     count
--------------------  -------
add_generators              1
build_bus_regions           1
build_load_weights          1
cluster_network             1
prepare_live_network        1
simplify_network            1
solve_network               1
total                       7

Select jobs to execute...

[Tue Apr  2 15:41:39 2024]
rule build_bus_regions:
    input: data/gb_shape.geojson, resources/offshore_shapes.geojson, data/ETYS_base.nc
    output: resources/regions_onshore.geojson, resources/regions_offshore.geojson
    log: logs/pypsa-lmp/build_bus_regions.log
    jobid: 5
    reason: Updated input files: data/ETYS_base.nc
    resources: tmpdir=C:\Users\alyden\AppData\Local\Temp, mem_mb=1000, mem_mib=954

[Tue Apr  2 15:43:24 2024]
Finished job 5.
1 of 7 steps (14%) done
Select jobs to execute...

[Tue Apr  2 15:43:24 2024]
rule add_generators:
    input: data/ETYS_base.nc, data/gb_shape.geojson, resources/bmunits_loc.csv, resources/regions_onshore.geojson, resources/regions_offshore.geojson, data/manual/carrier_costs.yaml
    output: resources/networks/gen.nc
    log: logs/pypsa-lmp/add_generators.log
    jobid: 2
    reason: Input files updated by another job: resources/regions_onshore.geojson, resources/regions_offshore.geojson
    resources: tmpdir=C:\Users\alyden\AppData\Local\Temp, mem_mb=1000, mem_mib=954

[Tue Apr  2 15:43:24 2024]
rule build_load_weights:
    input: resources/regions_onshore.geojson, data/gsp_geometries.geojson, data/gsp_gnode_directconnect_region_lookup.csv, data/FES-2021--Leading_the_Way--demandpk-all--gridsupplypoints.csv, data/FES-2021--Falling_Short--demandpk-all--gridsupplypoints.csv
    output: resources/load_weights.csv
    log: logs/pypsa-lmp/build_load_weights.log
    jobid: 7
    reason: Input files updated by another job: resources/regions_onshore.geojson
    resources: tmpdir=C:\Users\alyden\AppData\Local\Temp, mem_mb=1000, mem_mib=954

[Tue Apr  2 15:43:52 2024]
Error in rule build_load_weights:
    jobid: 7
    input: resources/regions_onshore.geojson, data/gsp_geometries.geojson, data/gsp_gnode_directconnect_region_lookup.csv, data/FES-2021--Leading_the_Way--demandpk-all--gridsupplypoints.csv, data/FES-2021--Falling_Short--demandpk-all--gridsupplypoints.csv
    output: resources/load_weights.csv
    log: logs/pypsa-lmp/build_load_weights.log (check log file(s) for error details)
    conda-env: C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\.snakemake\conda\cf0dbe1799d06fa5b5ff98f73b111298_

RuleException:
CalledProcessError in file C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\Snakefile, line 258:
Command 'C:/Users/alyden/AppData/Local/miniforge3/envs/pypsa-lmp/python.exe "C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\.snakemake\scripts\tmprrjutwk3.build_load_weights.py"' returned non-zero exit status 3221225786.
  File "C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\Snakefile", line 258, in __rule_build_load_weights
  File "C:\Users\alyden\AppData\Local\miniforge3\envs\pypsa-lmp\Lib\concurrent\futures\thread.py", line 58, in run
Terminating processes on user request, this might take some time.
[Tue Apr  2 15:43:52 2024]
Error in rule add_generators:
    jobid: 2
    input: data/ETYS_base.nc, data/gb_shape.geojson, resources/bmunits_loc.csv, resources/regions_onshore.geojson, resources/regions_offshore.geojson, data/manual/carrier_costs.yaml
    output: resources/networks/gen.nc
    log: logs/pypsa-lmp/add_generators.log (check log file(s) for error details)
    conda-env: C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\.snakemake\conda\cf0dbe1799d06fa5b5ff98f73b111298_

RuleException:
CalledProcessError in file C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\Snakefile, line 236:
Command 'C:/Users/alyden/AppData/Local/miniforge3/envs/pypsa-lmp/python.exe "C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\.snakemake\scripts\tmpsgyv5vhl.add_generators.py"' returned non-zero exit status 3221225786.
  File "C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\Snakefile", line 236, in __rule_add_generators
  File "C:\Users\alyden\AppData\Local\miniforge3\envs\pypsa-lmp\Lib\concurrent\futures\thread.py", line 58, in run
Complete log: .snakemake\log\2024-04-02T154139.216540.snakemake.log
