Config file config/config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Provided cores: 8
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                     count
--------------------  -------
add_generators              1
build_load_weights          1
cluster_network             1
prepare_live_network        1
simplify_network            1
solve_network               1
total                       6

Select jobs to execute...

[Tue Apr  2 15:45:21 2024]
rule add_generators:
    input: data/ETYS_base.nc, data/gb_shape.geojson, resources/bmunits_loc.csv, resources/regions_onshore.geojson, resources/regions_offshore.geojson, data/manual/carrier_costs.yaml
    output: resources/networks/gen.nc
    log: logs/pypsa-lmp/add_generators.log
    jobid: 2
    reason: Missing output files: resources/networks/gen.nc; Updated input files: data/ETYS_base.nc, resources/regions_offshore.geojson, resources/regions_onshore.geojson
    resources: tmpdir=C:\Users\alyden\AppData\Local\Temp, mem_mb=1000, mem_mib=954

[Tue Apr  2 15:45:21 2024]
rule build_load_weights:
    input: resources/regions_onshore.geojson, data/gsp_geometries.geojson, data/gsp_gnode_directconnect_region_lookup.csv, data/FES-2021--Leading_the_Way--demandpk-all--gridsupplypoints.csv, data/FES-2021--Falling_Short--demandpk-all--gridsupplypoints.csv
    output: resources/load_weights.csv
    log: logs/pypsa-lmp/build_load_weights.log
    jobid: 7
    reason: Missing output files: resources/load_weights.csv; Updated input files: resources/regions_onshore.geojson
    resources: tmpdir=C:\Users\alyden\AppData\Local\Temp, mem_mb=1000, mem_mib=954

[Tue Apr  2 15:45:56 2024]
Finished job 2.
1 of 6 steps (17%) done
[Tue Apr  2 15:45:58 2024]
Error in rule build_load_weights:
    jobid: 7
    input: resources/regions_onshore.geojson, data/gsp_geometries.geojson, data/gsp_gnode_directconnect_region_lookup.csv, data/FES-2021--Leading_the_Way--demandpk-all--gridsupplypoints.csv, data/FES-2021--Falling_Short--demandpk-all--gridsupplypoints.csv
    output: resources/load_weights.csv
    log: logs/pypsa-lmp/build_load_weights.log (check log file(s) for error details)
    conda-env: C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\.snakemake\conda\cf0dbe1799d06fa5b5ff98f73b111298_

RuleException:
CalledProcessError in file C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\Snakefile, line 258:
Command 'C:/Users/alyden/AppData/Local/miniforge3/envs/pypsa-lmp/python.exe "C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\.snakemake\scripts\tmpxi8mpazv.build_load_weights.py"' returned non-zero exit status 3221225786.
  File "C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\Snakefile", line 258, in __rule_build_load_weights
  File "C:\Users\alyden\AppData\Local\miniforge3\envs\pypsa-lmp\Lib\concurrent\futures\thread.py", line 58, in run
Terminating processes on user request, this might take some time.
Complete log: .snakemake\log\2024-04-02T154520.407689.snakemake.log
